files:
  - source: /simplified/en/**/*.md
    translation: /simplified/%two_letters_code%/**/%original_file_name%
  - source: /roadmap/en/**/*.md
    translation: /roadmap/%two_letters_code%/**/%original_file_name%
